[package]
name = "hashu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hashu"
path = "src/main.rs"

[dependencies]
hashu-core = { path = "../hashu-core" }
hashu-mint = { path = "../hashu-mint" }
hashu-proxy = { path = "../hashu-proxy" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
dialoguer = { workspace = true }
nostr = { workspace = true }
serde_json = { workspace = true }
bitcoin = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
